/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#f7f9fb",
        "on-tertiary-fixed": "#002113",
        "primary": "#0050cb",
        "on-primary-fixed": "#001849",
        "primary-container": "#0066ff",
        "outline-variant": "#c2c6d8",
        "surface-variant": "#e0e3e5",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "tertiary-container": "#008259",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#4edea3",
        "outline": "#727687",
        "on-secondary-fixed": "#001a42",
        "secondary": "#0058be",
        "secondary-fixed-dim": "#adc6ff",
        "error": "#ba1a1a",
        "surface-container-highest": "#e0e3e5",
        "secondary-container": "#2170e4",
        "on-tertiary-fixed-variant": "#005236",
        "on-surface-variant": "#424656",
        "primary-fixed-dim": "#b3c5ff",
        "on-surface": "#191c1e",
        "on-primary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#e1ffec",
        "on-error": "#ffffff",
        "inverse-primary": "#b3c5ff",
        "on-secondary-container": "#fefcff",
        "on-error-container": "#93000a",
        "surface-tint": "#0054d6",
        "surface-container-low": "#f2f4f6",
        "on-secondary-fixed-variant": "#004395",
        "secondary-fixed": "#d8e2ff",
        "on-primary-container": "#f8f7ff",
        "on-primary-fixed-variant": "#003fa4",
        "primary-fixed": "#dae1ff",
        "tertiary": "#006645",
        "surface-container": "#eceef0",
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "on-background": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2d3133",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-high": "#e6e8ea"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms'),
  ],
}
